name: Code Quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.12"

    - name: Install linters
      run: |
        pip install --upgrade pip
        pip install "ruff" "black" "isort"
        pip install poetry
        poetry install 

    - name: Ruff check
      run: ruff check .

    - name: Isort
      run: isort --check --profile black .

    - name: Black check
      run: black --check .

    - name: mypy check
      run: |
        mypy --install-types
        mypy . --explicit-package-bases