name: Code Quality
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - run: pip install --upgrade pip
    - run: pip install "ruff<1" "black<23" "isort<6" 
    - run: ruff check .
    - run: black --check .
    - run: isort --check --profile black .
